### ISSUE TITLE
02_IPA 05-Dec-2021/Question-2 is not passing the test cases

### ISSUE THREAD

**Issue by Manoj-Mukund** [harshitg123/TCS-Xplore-Python#3]
https://github.com/harshitg123/TCS-Xplore-Python/tree/d04105e9fe17855d3373cdee80677b8cea1fea52/02_IPA%2005-Dec-2021/Question-2

**Comment by harshitg123** [comment]
First of all, I'm very sorry to reply this late to your issue.

I read the question once again it is mentioned there to show the count of the first object only and right now I'm showing the count of all the objects.

I've now removed the loop and shown the count of the first object only.

Thanks for pointing out that issue.
