### ISSUE TITLE
02_ipa question 1 solution.py > line 13 :

### ISSUE THREAD

**Issue by pandab99** [harshitg123/TCS-Xplore-Python#5]
02_ipa question 1 solution.py > line 13 :
why did you put "-1 "
please explain , I didn't understood

**Comment by harshitg123** [comment]
First of all, I'm very sorry to reply this late to your issue.

There are 2 lines missing in the isPresent() function.

`else:
        return -1`

So, In case the user inputs the wrong string it will return -1 and will fall into the first condition of the if statement.
